<?php

namespace AppBundle\Repository;

/**
 * ArtefactRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactRepository extends \Doctrine\ORM\EntityRepository {
}
