<?php

namespace AppBundle\Repository;

/**
 * CanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanRepository extends \Doctrine\ORM\EntityRepository
{
}
