<?php

namespace AppBundle\Repository;

use Nines\UtilBundle\Repository\TermRepository;

/**
 * ContentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends TermRepository {
}
