<?php

namespace AppBundle\Repository;

/**
 * GlazeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlazeRepository extends \Doctrine\ORM\EntityRepository {
}
