<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Manufacturer;
use Nines\UtilBundle\Repository\TermRepository;

/**
 * ManufacturerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends TermRepository {

}
