<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Artefact;
use Doctrine\ORM\EntityRepository;

/**
 * ArtefactRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactRepository extends EntityRepository {
    /**
     * Do a typeahead-style query and return the results.
     *
     * @param string $q
     *
     * @return Artefact[]|Collection
     */
    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('v');
        $qb->where('v.catalogNumber like :q');
        $qb->setParameter('q', '%' . $q . '%');

        return $qb->getQuery()->execute();
    }
}
