<?php

namespace App\Repository;

use App\Entity\Artefact;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ArtefactRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactRepository extends ServiceEntityRepository {

    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Artefact::class);
    }

    /**
     * Do a typeahead-style query and return the results.
     *
     * @param string $q
     *
     * @return Artefact[]|Collection
     */
    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('v');
        $qb->where('v.catalogNumber like :q');
        $qb->setParameter('q', '%' . $q . '%');

        return $qb->getQuery()->execute();
    }
}
