<?php

namespace App\Repository;

use App\Entity\Artefact;
use App\Entity\Bottle;
use Doctrine\Persistence\ManagerRegistry;

/**
 * BottleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BottleRepository extends ArtefactRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Bottle::class);
    }

}
