<?php

namespace AppBundle\Repository;

/**
 * CeramicRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CeramicRepository extends ArtefactRepository {
}
