<?php

namespace App\Repository;

use App\Entity\Artefact;
use App\Entity\Ceramic;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CeramicRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CeramicRepository extends ArtefactRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Ceramic::class);
    }

}
