<?php

namespace App\Repository;

use App\Entity\Artefact;
use App\Entity\CircaDate;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CircaDateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircaDateRepository extends \Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, CircaDate::class);
    }

}
