<?php

namespace App\Repository;

use App\Entity\Artefact;
use App\Entity\Glaze;
use Doctrine\Persistence\ManagerRegistry;
use Nines\UtilBundle\Repository\TermRepository;

/**
 * GlazeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlazeRepository extends TermRepository {

    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Glaze::class);
    }

}
