<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\Repository;

use App\Entity\Institution;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * InstitutionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionRepository extends ServiceEntityRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Institution::class);
    }

    /**
     * Do a typeahead-style query and return the results.
     *
     * @param string $q
     *
     * @return Collection|Institution[]
     */
    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('v');
        $qb->where('v.name like :q');
        $qb->setParameter('q', '%' . $q . '%');

        return $qb->getQuery()->execute();
    }

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('v');
        $qb->where('MATCH(v.name, v.url) AGAINST (:q BOOLEAN) > 0');
        $qb->setParameter('q', $q);

        return $qb->getQuery();
    }
}
