<?php

namespace App\Repository;

use App\Entity\Artefact;
use App\Entity\Manufacturer;
use Doctrine\Persistence\ManagerRegistry;
use Nines\UtilBundle\Repository\TermRepository;

/**
 * ManufacturerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends TermRepository {

    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Manufacturer::class);
    }


}
