<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\Institution;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class InstitutionFixtures extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $item1 = new Institution();
        $item1->setName('SFU Archaeology Department');
        $item1->setUrl('http://www.sfu.ca/archaeology.html');
        $item1->setAddress('<p><strong>Department of Archaeology</strong><br />Simon Fraser University</p><p>Education Building 9635<br />8888 University Dr.<br />Burnaby, BC&nbsp; V5A 1S6</p>');
        $item1->setContact('<p>Phone: 778.782.3135<br />Fax: 778.782.5666<br />email: goarch@sfu.ca</p>');
        $this->addReference('_reference_Institution1', $item1);
        $manager->persist($item1);

        $item2 = new Institution();
        $item2->setName('Museum of Archaeology & Ethnology');
        $item2->setUrl('https://www.sfu.ca/archaeology/museum.html');
        $item2->setAddress('<p>NE Corner of the AQ<br />Saywell Atrium, off Saywell Hall<br />8888 University Dr.<br />Burnaby, BC &nbsp;V5A 1S6</p>');
        $this->addReference('_reference_Institution2', $item2);
        $manager->persist($item2);

        $item3 = new Institution();
        $item3->setName('Museum of Anthropology');
        $item3->setUrl('https://moa.ubc.ca/');
        $item3->setAddress('<p>6393 NW Marine Drive<br />Vancouver, BC, Canada V6T 1Z2</p>');
        $item3->setContact('<p>Email &bull; <a href="mailto:info@moa.ubc.ca">info@moa.ubc.ca</a><br />Phone &bull; <a href="tel:+16048225087">604.822.5087</a></p>');
        $this->addReference('_reference_Institution3', $item3);
        $manager->persist($item3);

        $item4 = new Institution();
        $item4->setName('Royal BC Museum');
        $item4->setUrl('https://royalbcmuseum.bc.ca/');
        $item4->setAddress('<p>675 Belleville Street,<br />Victoria, BC V8W 9W2</p>');
        $item4->setContact('<p><a href="tel:12503567226">1-250-356-7226</a><br /><a href="tel:18884477977">1-888-447-7977</a><br /><a href="mailto:reception@royalbcmuseum.bc.ca">reception@royalbcmuseum.bc.ca</a></p>');
        $this->addReference('_reference_Institution4', $item4);
        $manager->persist($item4);

        $item5 = new Institution();
        $item5->setName('Department of Anthropology, UBC');
        $item5->setUrl('https://anth.ubc.ca/');
        $item5->setAddress('<p>Department of Anthropology<br>Vancouver Campus<br>6303 NW Marine Drive<br>Vancouver, BC Canada<br>V6T 1Z1</p>');
        $item5->setContact('<p>Email <a href="mailto:Anth.Dept@ubc.ca">Anth.Dept@ubc.ca</a></p>');
        $this->addReference('_reference_Institution5', $item5);
        $manager->persist($item5);

        $manager->flush();
    }
}
