<?php

declare(strict_types=1);

/*
 * (c) 2021 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\Location;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LocationFixtures extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $item1 = new Location();
        $item1->setGeonameId('5911606');
        $item1->setLatitude('49.26636000');
        $item1->setLongitude('-122.95263000');
        $item1->setName('burnaby-bc');
        $item1->setLabel('Burnaby, BC');
        $item1->setDescription('<p>A city in British Columbia, Canada. Bordered by Vancouver on the west and New Westminster on the south.</p>');
        $this->addReference('_reference_Location1', $item1);
        $manager->persist($item1);

        $item2 = new Location();
        $item2->setGeonameId('3658666');
        $item2->setLatitude('-2.90055000');
        $item2->setLongitude('-79.00453000');
        $item2->setName('cuenca-ecuador');
        $item2->setLabel('Cuenca, Ecuador');
        $this->addReference('_reference_Location2', $item2);
        $manager->persist($item2);

        $item3 = new Location();
        $item3->setGeonameId('2178514');
        $item3->setLatitude('-10.55109000');
        $item3->setLongitude('161.82810000');
        $item3->setName('san-cristobal');
        $item3->setLabel('San Cristobal');
        $item3->setDescription('<p>Part of the Solomon Islands</p>');
        $this->addReference('_reference_Location3', $item3);
        $manager->persist($item3);

        $item4 = new Location();
        $item4->setGeonameId('6087844');
        $item4->setLatitude('49.20678000');
        $item4->setLongitude('-122.91092000');
        $item4->setName('new-westminster');
        $item4->setLabel('New Westminster');
        $this->addReference('_reference_Location4', $item4);
        $manager->persist($item4);

        $item5 = new Location();
        $item5->setGeonameId('3652350');
        $item5->setLatitude('-1.67098000');
        $item5->setLongitude('-78.64712000');
        $item5->setName('riobamba');
        $item5->setLabel('Riobamba');
        $this->addReference('_reference_Location5', $item5);
        $manager->persist($item5);

        $item6 = new Location();
        $item6->setLatitude('-0.51262800');
        $item6->setLongitude('-78.97504800');
        $item6->setName('las-pampas');
        $item6->setLabel('Las Pampas');
        $item6->setDescription('<p>Dig site in Reserva Ecologica Los Illinizas</p>');
        $this->addReference('_reference_Location6', $item6);
        $manager->persist($item6);

        $manager->flush();
    }
}
