<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\Vessel;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class VesselFixtures extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $item1 = new Vessel();
        $item1->setName('tile');
        $item1->setLabel('Tile');
        $item1->setDescription('Ceramic tile with glaze');
        $this->addReference('_reference_Vessel1', $item1);
        $manager->persist($item1);

        $item2 = new Vessel();
        $item2->setName('ornament');
        $item2->setLabel('Ornament');
        $item2->setDescription('Decorative ornament with glaze.');
        $this->addReference('_reference_Vessel2', $item2);
        $manager->persist($item2);

        $item3 = new Vessel();
        $item3->setName('vase');
        $item3->setLabel('Vase');
        $item3->setDescription('Open ceramic container with a shoulder and neck');
        $this->addReference('_reference_Vessel3', $item3);
        $manager->persist($item3);

        $item4 = new Vessel();
        $item4->setName('bowl');
        $item4->setLabel('Bowl');
        $item4->setDescription('A round ceramic dish or container.');
        $this->addReference('_reference_Vessel4', $item4);
        $manager->persist($item4);

        $manager->flush();
    }
}
