<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Glaze;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LoadGlaze extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) {
        $item1 = new Glaze();
        $item1->setName('ash-glaze');
        $item1->setLabel('Ash Glaze');
        $item1->setDescription('<p>Made from wood or plant ash, which contains potash and lime.</p>');
        $this->addReference('_reference_Glaze1', $item1);
        $manager->persist($item1);

        $item2 = new Glaze();
        $item2->setName('feldspathic');
        $item2->setLabel('Feldspathic');
        $item2->setDescription('<p>Glaze used on porcelain.</p>');
        $this->addReference('_reference_Glaze2', $item2);
        $manager->persist($item2);

        $item3 = new Glaze();
        $item3->setName('lead-glaze');
        $item3->setLabel('Lead Glaze');
        $item3->setDescription('<p>Lead-based glazes of various colours.</p>');
        $this->addReference('_reference_Glaze3', $item3);
        $manager->persist($item3);

        $item4 = new Glaze();
        $item4->setName('salt-glaze');
        $item4->setLabel('Salt-glaze');
        $item4->setDescription('<p>Transparent, glossy, salt-based glaze often applied to sotneware.</p>');
        $this->addReference('_reference_Glaze4', $item4);
        $manager->persist($item4);

        $manager->flush();
    }
}
