<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Manufacturer;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LoadManufacturer extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) {
        $item1 = new Manufacturer();
        $item1->setName('hutchinson');
        $item1->setLabel('Hutchinson');
        $item1->setDescription('Common glass bottle first used in 1894.');
        $this->addReference('_reference_Manufacturer1', $item1);
        $manager->persist($item1);

        $item2 = new Manufacturer();
        $item2->setName('root-glass-company');
        $item2->setLabel('Root Glass Company');
        $item2->setDescription('First manufacturer of the contour Coca Cola bottle. Located in Terre Haute, Indiana.');
        $this->addReference('_reference_Manufacturer2', $item2);
        $manager->persist($item2);

        $item3 = new Manufacturer();
        $item3->setName('owens-illinois-glass-company');
        $item3->setLabel('Owens-Illinois Glass Company');
        $item3->setDescription('Owner of the Root Glass Company from the 1930s on.');
        $this->addReference('_reference_Manufacturer3', $item3);
        $manager->persist($item3);

        $item4 = new Manufacturer();
        $item4->setName('karl-lagerfeld');
        $item4->setLabel('Karl Lagerfeld');
        $item4->setDescription('Fashion designer and creator of an aluminum Coca Cola bottle.');
        $this->addReference('_reference_Manufacturer4', $item4);
        $manager->persist($item4);

        $item5 = new Manufacturer();
        $item5->setName('vetropack');
        $item5->setLabel('Vetropack');
        $item5->setDescription('Glass bottle manufacturer based in the USA.');
        $this->addReference('_reference_Manufacturer5', $item5);
        $manager->persist($item5);

        $manager->flush();
    }
}
