<?php declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20191023173300 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE circa_date (id INT AUTO_INCREMENT NOT NULL, value VARCHAR(255) NOT NULL, start INT DEFAULT NULL, start_circa TINYINT(1) DEFAULT \'0\' NOT NULL, end INT DEFAULT NULL, end_circa TINYINT(1) DEFAULT \'0\' NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE artefact (id INT AUTO_INCREMENT NOT NULL, recovery_location_id INT DEFAULT NULL, recovery_date_id INT DEFAULT NULL, manufacture_location_id INT DEFAULT NULL, manufacture_date_id INT DEFAULT NULL, institution_id INT DEFAULT NULL, catalog_number VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, further_reading LONGTEXT DEFAULT NULL, note LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, category VARCHAR(255) NOT NULL, INDEX IDX_8D158D2DFFEA558 (recovery_location_id), INDEX IDX_8D158D2DF14EB5E4 (recovery_date_id), INDEX IDX_8D158D2D348C30E0 (manufacture_location_id), INDEX IDX_8D158D2D3E6BE89F (manufacture_date_id), INDEX IDX_8D158D2D10405986 (institution_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE artefact_ceramic (id INT NOT NULL, shape_id INT DEFAULT NULL, glaze_id INT DEFAULT NULL, paste VARCHAR(255) DEFAULT NULL, munsell VARCHAR(255) DEFAULT NULL, INDEX IDX_BA9F769A50266CBB (shape_id), INDEX IDX_BA9F769A16286FD8 (glaze_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reference (id INT AUTO_INCREMENT NOT NULL, publication_id INT DEFAULT NULL, artefact_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_AEA3491338B217A7 (publication_id), INDEX IDX_AEA34913B52412E3 (artefact_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE glaze (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_3DDDB147EA750E8 (label), FULLTEXT INDEX IDX_3DDDB1476DE44026 (description), FULLTEXT INDEX IDX_3DDDB147EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_3DDDB1475E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE publication (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, citation LONGTEXT NOT NULL, doi VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE artefact_can (id INT NOT NULL, manufacturer_id INT DEFAULT NULL, content_id INT DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, brand VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, INDEX IDX_315E4591A23B42D (manufacturer_id), INDEX IDX_315E459184A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE artefact_bottle (id INT NOT NULL, manufacturer_id INT DEFAULT NULL, content_id INT DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, brand VARCHAR(255) DEFAULT NULL, INDEX IDX_EEED6798A23B42D (manufacturer_id), INDEX IDX_EEED679884A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_FEC530A9EA750E8 (label), FULLTEXT INDEX IDX_FEC530A96DE44026 (description), FULLTEXT INDEX IDX_FEC530A9EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_FEC530A95E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_5288FD4FEA750E8 (label), FULLTEXT INDEX IDX_5288FD4F6DE44026 (description), FULLTEXT INDEX IDX_5288FD4FEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_5288FD4F5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institution (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, address LONGTEXT DEFAULT NULL, contact LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manufacturer (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_3D0AE6DCEA750E8 (label), FULLTEXT INDEX IDX_3D0AE6DC6DE44026 (description), FULLTEXT INDEX IDX_3D0AE6DCEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_3D0AE6DC5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, geoname_id VARCHAR(16) DEFAULT NULL, latitude NUMERIC(11, 8) DEFAULT NULL, longitude NUMERIC(11, 8) DEFAULT NULL, alternate_names LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', country_code VARCHAR(2) DEFAULT NULL, admin1 VARCHAR(20) DEFAULT NULL, admin2 VARCHAR(80) DEFAULT NULL, admin3 VARCHAR(20) DEFAULT NULL, admin4 VARCHAR(20) DEFAULT NULL, timezone VARCHAR(40) DEFAULT NULL, elevation INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_5E9E89CBEA750E8 (label), FULLTEXT INDEX IDX_5E9E89CB6DE44026 (description), FULLTEXT INDEX IDX_5E9E89CBEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_5E9E89CB5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, artefact_id INT DEFAULT NULL, original_name VARCHAR(64) NOT NULL, image_file_path VARCHAR(48) NOT NULL, thumbnail_path VARCHAR(48) NOT NULL, image_size INT NOT NULL, image_width INT DEFAULT NULL, image_height INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_C53D045FB52412E3 (artefact_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, status_id INT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, include_comments TINYINT(1) NOT NULL, searchable LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, excerpt LONGTEXT NOT NULL, content LONGTEXT NOT NULL, INDEX IDX_BA5AE01D12469DE2 (category_id), INDEX IDX_BA5AE01D6BF700BD (status_id), INDEX IDX_BA5AE01DA76ED395 (user_id), FULLTEXT INDEX blog_post_content (title, searchable), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, public TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_92121D87EA750E8 (label), FULLTEXT INDEX IDX_92121D876DE44026 (description), FULLTEXT INDEX IDX_92121D87EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_92121D875E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_CA275A0CEA750E8 (label), FULLTEXT INDEX IDX_CA275A0C6DE44026 (description), FULLTEXT INDEX IDX_CA275A0CEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_CA275A0C5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_page (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, weight INT NOT NULL, public TINYINT(1) NOT NULL, include_comments TINYINT(1) NOT NULL, title VARCHAR(255) NOT NULL, searchable LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, excerpt LONGTEXT NOT NULL, content LONGTEXT NOT NULL, INDEX IDX_F4DA3AB0A76ED395 (user_id), FULLTEXT INDEX blog_page_content (title, searchable), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE element (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, uri VARCHAR(190) NOT NULL, comment LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_41405E39EA750E8 (label), FULLTEXT INDEX IDX_41405E396DE44026 (description), FULLTEXT INDEX IDX_41405E39EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_41405E39841CB121 (uri), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_B1133D0EEA750E8 (label), FULLTEXT INDEX IDX_B1133D0E6DE44026 (description), FULLTEXT INDEX IDX_B1133D0EEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_B1133D0E5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_note (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, comment_id INT NOT NULL, content LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_E98B58F8A76ED395 (user_id), INDEX IDX_E98B58F8F8697D13 (comment_id), FULLTEXT INDEX commentnote_ft_idx (content), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment (id INT AUTO_INCREMENT NOT NULL, status_id INT NOT NULL, fullname VARCHAR(120) NOT NULL, email VARCHAR(120) NOT NULL, follow_up TINYINT(1) NOT NULL, entity VARCHAR(120) NOT NULL, content LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_9474526C6BF700BD (status_id), FULLTEXT INDEX comment_ft_idx (fullname, content), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nines_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', fullname VARCHAR(255) DEFAULT NULL, institution VARCHAR(255) DEFAULT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_5BA994A192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_5BA994A1A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_5BA994A1C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wbnt_dfgb_test (id INT AUTO_INCREMENT NOT NULL, testrelated_id INT DEFAULT NULL, name VARCHAR(60) DEFAULT NULL, INDEX IDX_A86F10518E63F6D6 (testrelated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wbnt_dfgb_testrelated (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE artefact ADD CONSTRAINT FK_8D158D2DFFEA558 FOREIGN KEY (recovery_location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE artefact ADD CONSTRAINT FK_8D158D2DF14EB5E4 FOREIGN KEY (recovery_date_id) REFERENCES circa_date (id)');
        $this->addSql('ALTER TABLE artefact ADD CONSTRAINT FK_8D158D2D348C30E0 FOREIGN KEY (manufacture_location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE artefact ADD CONSTRAINT FK_8D158D2D3E6BE89F FOREIGN KEY (manufacture_date_id) REFERENCES circa_date (id)');
        $this->addSql('ALTER TABLE artefact ADD CONSTRAINT FK_8D158D2D10405986 FOREIGN KEY (institution_id) REFERENCES institution (id)');
        $this->addSql('ALTER TABLE artefact_ceramic ADD CONSTRAINT FK_BA9F769A50266CBB FOREIGN KEY (shape_id) REFERENCES form (id)');
        $this->addSql('ALTER TABLE artefact_ceramic ADD CONSTRAINT FK_BA9F769A16286FD8 FOREIGN KEY (glaze_id) REFERENCES glaze (id)');
        $this->addSql('ALTER TABLE artefact_ceramic ADD CONSTRAINT FK_BA9F769ABF396750 FOREIGN KEY (id) REFERENCES artefact (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reference ADD CONSTRAINT FK_AEA3491338B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id)');
        $this->addSql('ALTER TABLE reference ADD CONSTRAINT FK_AEA34913B52412E3 FOREIGN KEY (artefact_id) REFERENCES artefact (id)');
        $this->addSql('ALTER TABLE artefact_can ADD CONSTRAINT FK_315E4591A23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id)');
        $this->addSql('ALTER TABLE artefact_can ADD CONSTRAINT FK_315E459184A0A3ED FOREIGN KEY (content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE artefact_can ADD CONSTRAINT FK_315E4591BF396750 FOREIGN KEY (id) REFERENCES artefact (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE artefact_bottle ADD CONSTRAINT FK_EEED6798A23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id)');
        $this->addSql('ALTER TABLE artefact_bottle ADD CONSTRAINT FK_EEED679884A0A3ED FOREIGN KEY (content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE artefact_bottle ADD CONSTRAINT FK_EEED6798BF396750 FOREIGN KEY (id) REFERENCES artefact (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FB52412E3 FOREIGN KEY (artefact_id) REFERENCES artefact (id)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01D12469DE2 FOREIGN KEY (category_id) REFERENCES blog_post_category (id)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01D6BF700BD FOREIGN KEY (status_id) REFERENCES blog_post_status (id)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01DA76ED395 FOREIGN KEY (user_id) REFERENCES nines_user (id)');
        $this->addSql('ALTER TABLE blog_page ADD CONSTRAINT FK_F4DA3AB0A76ED395 FOREIGN KEY (user_id) REFERENCES nines_user (id)');
        $this->addSql('ALTER TABLE comment_note ADD CONSTRAINT FK_E98B58F8A76ED395 FOREIGN KEY (user_id) REFERENCES nines_user (id)');
        $this->addSql('ALTER TABLE comment_note ADD CONSTRAINT FK_E98B58F8F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C6BF700BD FOREIGN KEY (status_id) REFERENCES comment_status (id)');
        $this->addSql('ALTER TABLE wbnt_dfgb_test ADD CONSTRAINT FK_A86F10518E63F6D6 FOREIGN KEY (testrelated_id) REFERENCES wbnt_dfgb_testrelated (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
        $this->throwIrreversibleMigrationException();
    }
}
